### ISSUE TITLE
Failed to download APT key for the Docker repository

### ISSUE THREAD

**Issue by penguineer** [netz39/ansible-role-host-docker#17]
Using this role in Ubuntu 24 LTS it get the following error

```
TASK [netz39.host_docker : Put docker apt release key in place] ****************
fatal: [diepa.prod.docker-1]: FAILED! => changed=false
dest: /etc/apt/keyrings/docker.asc
elapsed: 0
msg: 'An unknown error occurred: HTTPSConnection.__init__() got an unexpected keyword argument ''cert_file'''
url: https://download.docker.com/linux/debian/gpg
```

with setup
```
    - role: netz39.host_docker
      vars:
        docker_data_root: "/srv/docker"
        docker_cron_image_prune: true
```

My setup

```
→ ansible --version
ansible [core 2.14.18]
config file = None
configured module search path = ['/home/tux/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3/dist-packages/ansible
ansible collection location = /home/tux/.ansible/collections:/usr/share/ansible/collections
executable location = /usr/bin/ansible
python version = 3.11.2 (main, Nov 30 2024, 21:22:50) [GCC 12.2.0] (/usr/bin/python3)
jinja version = 3.1.2
libyaml = True
```
